version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: lyra-backend
    ports:
      - "8080:8080"
    env_file:
      - ./be/.env
    restart: unless-stopped

